### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by buddiex** [johnbrandborg/faker-events#5]
### Description
I get module not found error when I try the command.
```python -m faker_events -s app.py -n 1 ```

while app.py is in the working/root directory.

I found a way around this looking at the `faker_events.__main__.py` file. but I just wanted to raise to issue to get a chance to say this is a very cool library 👍 .

**Comment by johnbrandborg** [comment]
Thank you very much! 😄 I really appreciate the feedback @buddiex!  I will fix the issue and release a new version.
